# Week2授業前課題3 行列積のスクラッチ

## 目的
・数式演算ライブラリのNumPyに慣れる  
・行列演算に慣れる  

## 行列積
以下のような行列A、Bを考える。  
  
$$
        A =
        \left[\begin{array}{c}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
            7 & 8 & -9 \\
        \end{array}\right] ,
         \quad
         B = 
        \left[\begin{array}{c}
            0 & 2 & 1 \\
            0 & 2 & -8 \\
            2 & 9 & -1 \\
        \end{array}\right] \quad
$$
  
NumPyで表すと次のようになる。

>import numpy as np  
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])  
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])  

### 【問題1】行列積を手計算する
AとBの行列積を手計算で解く。
計算過程もマークダウンテキストを用いて説明する。

$$
        AB =
        \left[\begin{array}{c}
            -1*0 + 2*0 + 3*2 & -1*2 + 2*2 + 3*9 & -1*1 + 2*-8 + 3*-1 \\
            4*0  -5*0 + 6*2 & 4*2  -5*2 + 6*9 & 4*1  -5*-8 +6*-1 \\
            7*0 + 8*0 + 9*2 & 7*2 + 8*2   -9*9 & 3*1 + 6*-8  -9*-1 \\
        \end{array}\right] 
          = 
        \left[\begin{array}{c}
            6 & 29 & -20 \\
            14 & 52 & 38 \\
            -18 & -51 & -48 \\
        \end{array}\right] \quad
$$

### 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算出来る。  
これらを使い行列積を計算する。  
[numpy.matmul — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul)  
[numpy.dot — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)  
3種類の違い  
np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをする。  
今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されている。以下はnp.dot()の説明からの引用である。  
>If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

In [1]:
import numpy as np
arry_a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
arry_b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("arry_a:{}".format(arry_a))
print("arry_b:{}".format(arry_b))

arry_a:[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
arry_b:[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


In [2]:
print("arry_a・arry_b = {}".format(np.matmul(arry_a, arry_b)))

arry_a・arry_b = [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 行列積のスクラッチ実装
np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していく。これにより、行列積の計算に対する理解を深める。ここで考えるのは行列AとBのような次元が2の配列に限定する。

### 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。  
・行列Aの(0,0)の要素$ a_{0,0} $と行列Bの(0,0)の要素$ b_{0,0} $を掛け合わせる  
・行列Aの(0,1)の要素$ a_{0,1} $と行列Bの(1,0)の要素$ b_{1,0} $を掛け合わせる  
・行列Aの(0,2)の要素$ a_{0,2} $と行列Bの(2,0)の要素$ a_{2,0} $を掛け合わせる  
それらの値を全て足し合わせる  
数式で表すと  
$$
\sum_{k=0}^{2}a_{0,k}b_{k,0} \quad
$$
です。  
この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。  

In [3]:
ans = 0
ans += arry_a[0][0]*arry_b[0][0]
ans += arry_a[0][1]*arry_b[1][0]
ans += arry_a[0][2]*arry_b[2][0]
print("計算結果:{}".format(ans))
print("matmul関数を用いた場合： {}".format(np.matmul(arry_a, arry_b)[0][0]))

計算結果:6
matmul関数を用いた場合： 6


### 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させる。行列AとBを引数に受け取り、行列積を返す関数とする。  
行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになる。  
計算結果である $ 3 * 3 $の行列Cの各要素$ c_{i,j} $は数式で表すと次のようになる。  
  
$$
c_{i,j} = \sum_{k=0}^{2}a_{i,k}b_{k,j} \quad
$$
  
for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できる。インデックス$ i $や$ j $を1増やすと、次の行や列に移ることができる。

In [4]:
# 【問題4】行列積を行う関数の作成

def calc_dot(arry_a,arry_b):
    #import numpy as np  # 関数の中でimportはしない！

    # 各行列の行数、列数を格納する
    m = arry_a.shape[0]
    n = arry_a.shape[1]
    p = arry_b.shape[1]
    
    # 計算結果を格納する行列を初期化する 
    arry_ans = np.zeros((m, p))
    
    for i in range(p):
        #print(i)
        for j in range(m):
            temp = 0
            for k in range(n):
                #print("j:{} k: {}".format(j, k))
                #print("A:{}".format(arry_a[j][k]))
                #print("B:{}".format(arry_b[k][i]))
                #print("ab:{}".format(arry_a[j][k]*arry_b[k][i]))
                temp += arry_a[j][k]*arry_b[k][i]
                #print("ans[i][j]:{}".format(temp))
                #print("-"*70)
            arry_ans[j][i] = temp
    return arry_ans

#### 検証

In [5]:
print(calc_dot(arry_a, arry_b ))
array_test_c =np.array([[0, 1], [-10, -48], [14, 72]])
print("(matmul)arry_b・arry_a = {}".format(np.matmul(arry_b, arry_a)))
print("(calc_dot)arry_b・arry_a = {}".format(calc_dot(arry_b, arry_a)))
print("(matmul)arry_a・arry_a = {}".format(np.matmul(arry_a, arry_a)))
print("(calc_dot)arry_a・arry_a = {}".format(calc_dot(arry_a, arry_a)))
print("(matmul)arry_b・arry_b = {}".format(np.matmul(arry_b, arry_b)))
print("(calc_dot)arry_b・arry_b = {}".format(calc_dot(arry_b, arry_b)))
print("(matmul)arry_b・array_test_c= {}".format(np.matmul(arry_b, array_test_c)))
print("(calc_dot)arry_b・array_test_c = {}".format(calc_dot(arry_b, array_test_c)))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
(matmul)arry_b・arry_a = [[ 15  -2   3]
 [-48 -74  84]
 [ 27 -49  69]]
(calc_dot)arry_b・arry_a = [[ 15.  -2.   3.]
 [-48. -74.  84.]
 [ 27. -49.  69.]]
(matmul)arry_a・arry_a = [[ 30  12 -18]
 [ 18  81 -72]
 [-38 -98 150]]
(calc_dot)arry_a・arry_a = [[ 30.  12. -18.]
 [ 18.  81. -72.]
 [-38. -98. 150.]]
(matmul)arry_b・arry_b = [[  2  13 -17]
 [-16 -68  -8]
 [ -2  13 -69]]
(calc_dot)arry_b・arry_b = [[  2.  13. -17.]
 [-16. -68.  -8.]
 [ -2.  13. -69.]]
(matmul)arry_b・array_test_c= [[  -6  -24]
 [-132 -672]
 [-104 -502]]
(calc_dot)arry_b・array_test_c = [[  -6.  -24.]
 [-132. -672.]
 [-104. -502.]]


matmul関数と同じ結果になるので、問題ないようである。

## 行列積が定義されない組み合わせの行列
次に以下のような例を考える。
$$
        D =
        \left[\begin{array}{c}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
        \end{array}\right] ,
        E = 
        \left[\begin{array}{c}
            -9 & 8 & 7 \\
            6 & -5 & 4 \\
        \end{array}\right] \quad
$$
  
>d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])  
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])  
  
行列積DEはDの列数とEの行数が等しい場合に定義されているので、この例では計算ができない。

### 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性がある。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示される。
if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加える。

In [6]:
# 【問題5】計算が定義されない入力を判定する

def calc_dot_fix(arry_a,arry_b):
    # import numpy as np  # 関数の中でimportはしない！
    #print("a")
    #print(arry_a.shape[0])
    m = arry_a.shape[0]
    n = arry_a.shape[1]
    #print(arry_b.shape[1])
    p = arry_b.shape[1]
    # 行列Aの行数と行列Bの列数が等しくない場合、メッセージを表示する
    if arry_a.shape[1] != arry_b.shape[0]:
        print("行列積が計算できません。入力した行列の行数、列数を確認してください。")
        return
    arry_ans = np.zeros((m, p))
    #print(arry_ans)
    for i in range(p):
        #print(i)
        for j in range(m):
            temp = 0
            for k in range(n):
                #print("j:{} k: {}".format(j, k))
                #print("A:{}".format(arry_a[j][k]))
                #print("B:{}".format(arry_b[k][i]))
                #print("ab:{}".format(arry_a[j][k]*arry_b[k][i]))
                temp += arry_a[j][k]*arry_b[k][i]
                #print("ans[i][j]:{}".format(temp))
                #print("-"*70)
            arry_ans[j][i] = temp
    return arry_ans

In [7]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print(calc_dot_fix(d_ndarray, e_ndarray))

行列積が計算できません。入力した行列の行数、列数を確認してください。
None


### 【問題6】転置
片方の行列を転置することで、行列積が計算できるようにる。  
np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算する。  
[numpy.transpose — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html)  
[numpy.ndarray.T — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html)  

In [8]:
print("d_ndarray.T・e_ndarray:{}".format(calc_dot_fix(d_ndarray.T, e_ndarray)))

d_ndarray.T・e_ndarray:[[ 33. -28.   9.]
 [-48.  41.  -6.]
 [  9.  -6.  45.]]


#### 【おまけ】yukitakamoriさんの良いとこどりversion
for文がひとつ要らなくなる！さすがyukitakamoriさん！

In [9]:
# 【問題4】行列積を行う関数の作成、【問題5】計算が定義されない入力を判定する_t

def calc_dot_fix_t(arry_a,arry_b):
   # import numpy as np  # 関数の中でimportはしない！

    m = arry_a.shape[0]
    n = arry_a.shape[1]
    #print(arry_b.shape[1])
    p = arry_b.shape[1]
    # 行列Aの行数と行列Bの列数が等しくない場合、メッセージを表示する
    if arry_a.shape[1] != arry_b.shape[0]:
        print("行列積が計算できません。入力した行列の行数、列数を確認してください。")
        return
    arry_ans = np.zeros((m, p))
    for i in range(p):
        for j in range(m):
            # ここでfor文でループせず、行と列を掛けて、sumで合計する
            #print(arry_a[j]*arry_b[:, i])
            arry_ans[j][i] = sum(arry_a[j]*arry_b[:, i])
    return arry_ans

In [10]:
print(calc_dot_fix_t(arry_a, arry_b ))
array_test_c =np.array([[0, 1], [-10, -48], [14, 72]])
print("(matmul)arry_b・arry_a = {}".format(np.matmul(arry_b, arry_a)))
print("(calc_dot_fix_t)arry_b・arry_a = {}".format(calc_dot_fix_t(arry_b, arry_a)))
print("(matmul)arry_a・arry_a = {}".format(np.matmul(arry_a, arry_a)))
print("(calc_dot_fix_t)arry_a・arry_a = {}".format(calc_dot_fix_t(arry_a, arry_a)))
print("(matmul)arry_b・arry_b = {}".format(np.matmul(arry_b, arry_b)))
print("(calc_dot_fix_t)arry_b・arry_b = {}".format(calc_dot_fix_t(arry_b, arry_b)))
print("(matmul)arry_b・array_test_c= {}".format(np.matmul(arry_b, array_test_c)))
print("(calc_dot_fix_t)arry_b・array_test_c = {}".format(calc_dot_fix_t(arry_b, array_test_c)))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
(matmul)arry_b・arry_a = [[ 15  -2   3]
 [-48 -74  84]
 [ 27 -49  69]]
(calc_dot_fix_t)arry_b・arry_a = [[ 15.  -2.   3.]
 [-48. -74.  84.]
 [ 27. -49.  69.]]
(matmul)arry_a・arry_a = [[ 30  12 -18]
 [ 18  81 -72]
 [-38 -98 150]]
(calc_dot_fix_t)arry_a・arry_a = [[ 30.  12. -18.]
 [ 18.  81. -72.]
 [-38. -98. 150.]]
(matmul)arry_b・arry_b = [[  2  13 -17]
 [-16 -68  -8]
 [ -2  13 -69]]
(calc_dot_fix_t)arry_b・arry_b = [[  2.  13. -17.]
 [-16. -68.  -8.]
 [ -2.  13. -69.]]
(matmul)arry_b・array_test_c= [[  -6  -24]
 [-132 -672]
 [-104 -502]]
(calc_dot_fix_t)arry_b・array_test_c = [[  -6.  -24.]
 [-132. -672.]
 [-104. -502.]]


In [11]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print(calc_dot_fix_t(d_ndarray, e_ndarray))

行列積が計算できません。入力した行列の行数、列数を確認してください。
None


In [12]:
print("d_ndarray.T・e_ndarray:{}".format(calc_dot_fix_t(d_ndarray.T, e_ndarray)))

d_ndarray.T・e_ndarray:[[ 33. -28.   9.]
 [-48.  41.  -6.]
 [  9.  -6.  45.]]
