# Week4授業前課題3 オブジェクト指向の活用

In [3]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

In [4]:
data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)
X_std

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


array([[ 0.86828953,  0.65207831, -0.48795004, -0.26726124],
       [ 0.14471492, -1.06391725, -0.48795004, -0.26726124],
       [-0.57885968, -0.37751902, -1.46385011, -0.26726124],
       [-0.94064699, -0.72071813,  0.48795004, -0.26726124],
       [ 0.50650222,  0.99527742, -0.48795004, -0.26726124],
       [ 1.95365143,  2.02487476,  2.43975018,  2.40535118],
       [-0.94064699,  0.3088792 , -0.48795004,  1.06904497],
       [ 0.50650222,  0.3088792 ,  0.48795004, -0.26726124],
       [-1.66422159, -1.40711636, -0.48795004, -0.26726124],
       [ 0.14471492, -0.72071813,  0.48795004, -1.60356745]])

## 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。

Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

<pre>
pandas             DataFrame  Series  
matplotlib         ListedColormap  
scikit-learn       LinaerRegression  

## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。

最低でもそれぞれ5つ以上答えてください。

.fit  
.sum  
.fit_transform  
.reshape  
.astype   
.append  
.std  
.mean 

## 【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。

今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。

インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。

In [6]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """

        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_std = np.std(X, axis=0)
        X_scaled = (X - self.mean_) / X_std
        
        
        return X_scaled

In [7]:
data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scaler.mean_))
print("分散 : {}".format(scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [8]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2

example = ExampleClass(5)
print("value :", example.value)
example.add(3)
print("value :", example.value)

初期値5が設定されました
value : 5
value : 8


## 【問題4】 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。

コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。

クラス名や説明文も適切に書き換えてください。

In [10]:
class Subtraction():
    """引き算を行うクラス
    
    初期値を設定：values
    
    引き算の結果を返す
    
    """
    
    def __init__(self, value):
        if type(value) is int or type(value) is float: 
            self.value = value
            print("初期値{}を設定".format(self.value))
        else:
            print("int型かfloat型を指定してください")
            self.value = 0
        
    def sub(self, value):
        self.value -= value
test_sub = Subtraction(10)
print(test_sub.value)
test_sub.sub(5)
print(test_sub.value)

初期値10を設定
10
5


In [17]:
class Multiplication():
    """掛け算を行うクラス
    
    初期値を設定：values
    
    掛け算の結果を返す
    """
    
    def __init__(self, value):
        if type(value) is int or type(value) is float: 
            self.value = value
            print("初期値{}を設定".format(self.value))
        else:
            print("int型かfloat型を指定してください")
            self.value = 0
        
    def multi(self, value):
        self.value *= value
test_mul = Multiplication(10)
print(test_mul.value)
test_mul.multi(5)
print(test_mul.value)

初期値10を設定
10
50


In [18]:
class Division():
    """割り算を行うクラス
    
    初期値を設定：values
    
    割り算の結果を返す"""
    
    def __init__(self, value):
        if type(value) is int or type(value) is float: 
            self.value = value
            print("初期値{}を設定".format(self.value))
        else:
            print("int型かfloat型を指定してください")
            self.value = 0
        
    def divi(self, value):
        self.value /= value
test_di = Division(10)
print(test_di.value)
test_di.divi(5)
print(test_di.value)

初期値10を設定
10
2.0
